splot "potgauss0.5.dat" w l
splot "potgauss0.7.dat" w l
splot "potgauss0.9.dat" w l
splot "potgauss1.1.dat" w l
splot "potgauss1.3.dat" w l
splot "potgauss1.5.dat" w l
splot "potgauss1.7.dat" w l
splot "potgauss1.9.dat" w l
splot "potgauss2.1.dat" w l
splot "potgauss2.3.dat" w l
splot "potgauss2.5.dat" w l
splot "potgauss2.7.dat" w l
splot "potgauss2.9.dat" w l
